#!/usr/bin/env bash
# Writes config.php (gitignored, mode 600) from the database section of ~/.password. Prints no values.
set -euo pipefail
umask 077
cd "$(dirname "$0")/.."
source scripts/lib/dbcred.sh
load_db_credentials
esc() { local s=${1//\\/\\\\}; printf '%s' "${s//\'/\\\'}"; }
tmp="$(mktemp ./.config.XXXXXX)"
trap 'rm -f "$tmp"' EXIT
printf '<?php\n// Generated by scripts/make-config.sh. Do not commit.\nreturn [\n' > "$tmp"
printf "  'host' => '%s',\n" "$(esc "$DB_HOST")" >> "$tmp"
printf "  'port' => %d,\n" "$DB_PORT" >> "$tmp"
printf "  'name' => '%s',\n" "$(esc "$DB_NAME")" >> "$tmp"
printf "  'user' => '%s',\n" "$(esc "$DB_USER")" >> "$tmp"
printf "  'password' => '%s',\n" "$(esc "$DB_SECRET")" >> "$tmp"
printf '];\n' >> "$tmp"
mv "$tmp" config.php
chmod 600 config.php
echo "config.php written"
